export const productsModule = {
    state: {
        productList: [
            {
              id: 0,
              img: 'https://inksoft.ugp.io/images/products/2570/products/763/White/front/500.png?decache=633',
              type: 'shirt',
              name: 'White',
              stock: 100,
              price: '15000',
              sale: true,
              discount: '2.000',
            },
            {
              id: 1,
              img: 'https://inksoft.ugp.io/images/products/2570/products/763/Black/front/500.png?decache=760',
              type: 'shirt',
              name: 'Black',
              stock: 100,
              price: '15000',
              sale: true,
              discount: '2.000',
            },
            {
              id: 2,
              img: 'https://inksoft.ugp.io/images/products/2570/products/763/Antique_Irish_Green/front/500.png?decache=760',
              type: 'shirt',
              name: 'Irish-green',
              stock: 100,
              price: '15000',
              sale: false,
              discount: '0',
            },
            {
              id: 3,
              img: 'https://inksoft.ugp.io/images/products/2570/products/763/Coral_Silk/front/500.png?decache=423',
              type: 'shirt',
              name: 'Coral-silk',
              stock: 100,
              price: '15000',
              sale: false,
              discount: '0',
            },
            {
              id: 4,
              img: 'https://inksoft.ugp.io/images/products/2570/products/763/Heather_Red/front/500.png?decache=423',
              type: 'shirt',
              name: 'Heather-red',
              stock: 100,
              price: '15000',
              sale: false,
              discount: '0',
            },
            {
              id: 5,
              img: 'https://inksoft.ugp.io/images/products/2570/products/763/Heather_Sapphire/front/500.png?decache=423',
              type: 'shirt',
              name: 'Heather-sapphire',
              stock: 100,
              price: '15000',
              sale: false,
              discount: '0',
            },
            {
              id: 6,
              img: 'https://inksoft.ugp.io/images/products/2570/products/763/Lilac/front/500.png?decache=373',
              type: 'shirt',
              name: 'Lilac',
              stock: 100,
              price: '15000',
              sale: false,
              discount: '0',
            },
            {
              id: 7,
              img: 'https://inksoft.ugp.io/images/products/2570/products/763/Lime/front/500.png?decache=373',
              type: 'shirt',
              name: 'Lime',
              stock: 100,
              price: '15000',
              sale: false,
              discount: '0',
            },
            {
              id: 8,
              img: 'https://inksoft.ugp.io/images/products/2570/products/763/Mint_Green/front/500.png?decache=373',
              type: 'shirt',
              name: 'Mint-green',
              stock: 100,
              price: '15000',
              sale: false,
              discount: '0',
            },
            {
              id: 9,
              img: 'https://inksoft.ugp.io/images/products/2570/products/763/Purple/front/500.png?decache=740',
              type: 'shirt',
              name: 'Purple',
              stock: 100,
              price: '15000',
              sale: false,
              discount: '0',
            },
            {
              id: 10,
              img: 'https://inksoft.ugp.io/images/products/2570/products/763/Safety_Green/front/500.png?decache=740',
              type: 'shirt',
              name: 'Safety-green',
              stock: 100,
              price: '15000',
              sale: false,
              discount: '0',
            },
            {
              id: 11,
              img: 'https://inksoft.ugp.io/images/products/2570/products/763/Safety_Orange/front/500.png?decache=740',
              type: 'shirt',
              name: 'Safety-orange',
              stock: 100,
              price: '15000',
              sale: false,
              discount: '0',
            },
            {
              id: 12,
              img: 'https://inksoft.ugp.io/images/products/2570/products/763/Safety_Pink/front/500.png?decache=740',
              type: 'shirt',
              name: 'Safety-pink',
              stock: 100,
              price: '15000',
              sale: false,
              discount: '0',
            },
            {
              id: 13,
              img: 'https://inksoft.ugp.io/images/products/2570/products/763/Sport_Grey/front/500.png?decache=467',
              type: 'shirt',
              name: 'Sport-grey',
              stock: 100,
              price: '15000',
              sale: false,
              discount: '0',
            },
            {
              id: 14,
              img: 'https://inksoft.ugp.io/images/products/2570/products/763/Sunset/front/500.png?decache=633',
              type: 'shirt',
              name: 'Sunset',
              stock: 100,
              price: '15000',
              sale: false,
              discount: '0',
            },
            {
              id: 15,
              img: 'https://inksoft.ugp.io/images/products/2570/products/763/Turf_Green/front/500.png?decache=633',
              type: 'shirt',
              name: 'Turf-green',
              stock: 100,
              price: '15000',
              sale: false,
              discount: '0',
            },
            {
              id: 16,
              img: 'https://inksoft.ugp.io/images/products/2570/products/763/Violet/front/500.png?decache=633',
              type: 'shirt',
              name: 'Violet',
              stock: 100,
              price: '15000',
              sale: false,
              discount: '0',
            },
          ]
    }
}